# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Taisenki's Babylon
tagline:          'A Jekyll theme'
description:      'Taisenki's personal blog.'
baseurl:          /blog

author:
  name:           'Taisenki'
  url:            https://github.com/taisenki

paginate:         5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            3.4.1
sidebar_home_link:  true
github:             https://github.com/taisenki
  repo:             https://github.com/taisenki
